config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'
  resources :projects
  resources :tasks
  resources :steps
  get '/auth/:provider/callback', to: 'authentications#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  has_many :steps, through: :tasks
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_many :steps
end

app/models/user.rb
class User < ApplicationRecord
  has_one :authentication

  def User.update_from_oauth(oauth_hash)
    oauth_email = oauth_hash['extra']['raw_info']['email']
    user = User.find_by(email: oauth_email)

    if user.nil?
      oauth_juicy_bits = oauth_hash['extra']['raw_info']
      user = User.create(
        firstname: oauth_juicy_bits['name'].split(' ')[0],
        lastname: oauth_juicy_bits['name'].split(' ')[1],
        email: oauth_juicy_bits['email']
      )
      user.build_authentication(
        provider: oauth_hash['provider'],
        uid: oauth_juicy_bits['id'],
        token: oauth_hash['credentials']['token']
      )
      user.save
    else
      # User is already in DB
      # Update information and set @current_user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    User.update_from_oauth(auth)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    binding.pry
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def show
    @step = Step.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def show
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/authentications/create.html.erb
<h1>Authentications#create</h1>
<p>Find me in app/views/authentications/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<h1>Projects Index</h1>

<ul>
  <% @projects.each do |project| %>
    <li>
      <%= link_to project.title, project_path(project) %>
    </li>
  <% end %>
</ul>

app/views/projects/show.html.erb
<h1>Project Show</h1>


<h4><%= @project.title %></h4>
<h4><%= @project.github_url %></h4>
<h4>Due Date: <%= @project.due_date %></h4>
<h2>Project Tasks:</h2>
<ul>
  <% @project.tasks.each do |task| %>
  <li><%= link_to task.name, task_path(task) %></li>
  <% end %>
</ul>

app/views/steps/show.html.erb
<h3>Step#Show</h3>
<h2><%= @step.name %></h2>
<h4>Description: <%= @step.description %></h4>

app/views/tasks/show.html.erb
<h1>Task Show</h1>


<h4><%= @task.name %></h4>
<h4>Due Date: <%= @task.due_date %></h4>
<h2>Project Tasks:</h2>
<ul>
  <% @task.steps.each do |step| %>
  <li><%= link_to step.name, step_path(step) %></li>
  <% end %>
</ul>